version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: nouchka/sqlite3:latest # O una imagen que necesites
    platform: linux/amd64 # Especifica la plataforma aquí
    volumes:
      - db_data:/var/lib/sqlite
    networks:
      - app-network

  web:
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:

